<a href="https://colab.research.google.com/github/ntdthanh1409/B-i-t-p-ch-ng-4/blob/master/B%E1%BA%A3n_sao_c%E1%BB%A7a_bai_tap_sinh_mau_ngau_nhien.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Sử dụng thư viện Numpy

1. Sinh mẫu ngẫu nhiên bằng hàm arange trong khoảng [-15, 27] với khoảng cách là 0.7 và in kết quả ra màn hình

In [8]:
import numpy as np

In [5]:
#Code 
sample_1 = np.arange(-15, 27, 0.7)
sample_1

array([-15. , -14.3, -13.6, -12.9, -12.2, -11.5, -10.8, -10.1,  -9.4,
        -8.7,  -8. ,  -7.3,  -6.6,  -5.9,  -5.2,  -4.5,  -3.8,  -3.1,
        -2.4,  -1.7,  -1. ,  -0.3,   0.4,   1.1,   1.8,   2.5,   3.2,
         3.9,   4.6,   5.3,   6. ,   6.7,   7.4,   8.1,   8.8,   9.5,
        10.2,  10.9,  11.6,  12.3,  13. ,  13.7,  14.4,  15.1,  15.8,
        16.5,  17.2,  17.9,  18.6,  19.3,  20. ,  20.7,  21.4,  22.1,
        22.8,  23.5,  24.2,  24.9,  25.6,  26.3,  27. ])

2. Sinh mẫu ngẫu nhiên theo phân phối chuẩn với mean = 2.7 std = 1.2 và size = 40
In kết quả ra màn hình

In [7]:
#Code
sample_2 = np.random.normal(loc = 2.7, scale = 1.20, size = 40)
sample_2

array([1.47271358, 3.17210565, 2.83914364, 1.90499154, 4.63652263,
       2.90944734, 1.74269636, 1.09290125, 2.15470901, 3.27685103,
       2.86856234, 4.46497509, 0.98258119, 0.88957065, 2.31750605,
       1.9476006 , 3.48557322, 1.2003602 , 1.2389227 , 3.06895158,
       2.04534763, 2.21919624, 4.95329361, 1.65951283, 2.21885318,
       1.59697056, 2.39911951, 5.18404535, 3.46596123, 4.29449224,
       3.27479293, 1.05999005, 4.43969335, 2.71458351, 3.46366147,
       2.70877476, 4.37636355, 4.46941903, 0.61948584, 3.20139266])

3. Sinh mẫu ngẫu nhiên từ vector ['Viet Nam', 'Britain', 'France', 'Russia', 'Singapore'] 

với kích thước là 17 theo phân phối chuẩn

In [10]:
#Code
sample_3 = np.random.choice(['Viet Nam', 'Britain', 'France', 'Russia', 'Singapore'], 17)
sample_3

array(['Russia', 'Singapore', 'Singapore', 'Singapore', 'Britain',
       'Russia', 'Viet Nam', 'Viet Nam', 'Singapore', 'Russia',
       'Viet Nam', 'Viet Nam', 'Viet Nam', 'Viet Nam', 'Viet Nam',
       'Viet Nam', 'Viet Nam'], dtype='<U9')

4. Sinh mẫu ngẫu nhiên ở câu 3 nhưng không theo phân phối chuẩn mà theo 1 vector đặc tả giá trị xác suất do bạn chọn

In [13]:
#Code
sample_4 = np.random.choice(['Viet Nam', 'Britain', 'France', 'Russia', 'Singapore'], 6, p = [0.1, 0.3, 0.2, 0.2,0.2])
print(sample_4)

['Russia' 'France' 'France' 'Russia' 'Russia' 'France']


Sử dụng thư việc scipy.stats để sinh mẫu ngẫu nhiên

1. Sinh mẫu ngẫu nhiên theo phân phối chuẩn với mean = 12.7, std = 2.6 và size = 30. In kết quả ra màn hình

In [15]:
from scipy import stats

In [16]:
#Code
sample_5 = stats.norm.rvs(loc = 12.7, scale = 2.6, size = 30)
sample_5

array([13.80275698, 13.72465803, 14.79069586, 14.63971321, 12.31521648,
       14.05461696, 11.61557594,  6.1533127 , 13.729625  , 12.97913818,
       10.7844547 , 13.4388061 , 15.18317289, 17.36609588, 14.6273338 ,
       15.73082925, 11.46427774, 11.996609  , 14.67650462, 15.87473864,
       12.76341466, 11.20092762, 15.79902227, 13.67918398, 17.75638705,
       13.4119121 , 12.84213638, 10.31770335, 14.61104561, 11.51245153])

2. Hãy sinh một mẫu ngẫu nhiên theo phân phối Poisson

In [18]:
#Code
sample_6 = stats.poisson.rvs(loc=18,
                              mu=30,
                              size=10)
sample_6

array([54, 42, 49, 55, 35, 49, 53, 45, 45, 57])