<a href="https://colab.research.google.com/github/ntdthanh1409/B-i-t-p-ch-ng-4/blob/master/huong_dan_tao_du_lieu_mo_phong_ngau_nhien.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

TẠO DỮ LIỆU MÔ PHỎNG

Tạo dữ liệu mô phỏng là một kỹ năng cần thiết của người làm khoa học dữ liệu. 

Bài học này điểm lại một số hàm phổ biến thường được sử dụng để sinh dữ liệu mô phỏng

1. Thư viện numpy 

In [ ]:
import numpy as np

#Thiết lập random seed (mục đích để làm gì? - các bạn sv tìm hiểu thêm)
np.random.seed(1234)

#Sinh ngẫu nhiên dữ liệu theo phân phối chuẩn với các giá trị trung bình (mean), độ lệch chuẩn (standard deviation) và
#kích thước tập dữ liệu được sinh ra (size)
sample_1 = np.random.normal(loc = 5.5, scale = 2.7, size = 100)

#Sinh ngẫu nhiên mẫu thứ 2
sample_2 = np.random.normal(loc = 6.7, scale = 3.2, size = 100)

In [ ]:
#Xuất dữ liệu của sample_1
print(sample_1[:10])

[ 6.77287494  2.28436562  9.36830881  4.65583988  3.55441042  7.89533994
  7.82088872  3.78138654  5.5423802  -0.55524938]


In [ ]:
#Xuất dữ liệu của sample_2
print(sample_2[:10])

[ 7.63185715  8.51290783  8.31149363  7.61294619  8.24972196 11.06314084
  4.20046309  5.20234347 10.61863794  2.60045352]


2. Hàm arange

Có mục đích là sinh dữ liệu có giá trị cách đều nhau trong một khoảng giá trị cho trước.

numpy.arange([start, ]stop, [step, ]dtype=None, *, like=None)

start (cận dưới) mặc định là 0; stop là cận trên; step khoảng cách giữa các giá trị (mặc định là 1); 

In [ ]:
#Sinh dữ liệu từ 0 tới 15 với khoảng cách giữa các phần tử mặc định là 1
sample_3 = np.arange(15)
print(sample_3)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [ ]:
#Sinh dữ liệu từ -7 đến 15 với khoảng cách là 1.5
sample_4 = np.arange(-7, 15, 1.5)
print(sample_4)

[-7.  -5.5 -4.  -2.5 -1.   0.5  2.   3.5  5.   6.5  8.   9.5 11.  12.5
 14. ]


3. Hàm choice

Sinh ngẫu nhiên một mẫu từ một mảng 1 chiều.

random.choice(a, size=None, replace=True, p=None)

Trong đó:

- a là một mảng 1 chiều (vector) hay một số nguyên (khi này hoạt động tương tự hàm arange)
- size là kích thước mẫu được sinh ra
- replace
- p là mảng 1 chiều đặc tả xác suất tương ứng với mỗi phần tử của a. Nếu không có p thì mặc định sinh ngẫu nhiên theo phân phối chuẩn

In [ ]:
#Sinh ngẫu nhien theo phân phối chuẩn 10 phần tử có giá trị lớn nhất (cận trên là 15)
sample_5 = np.random.choice(15, 10)
print(sample_5)

[14  7  6  3  3 12 12 10 14  0]


In [ ]:
#Sinh ngẫu nhiên chuỗi số [-1, 2, 3, 4, 5] với kích thước là 30 theo phân phối chuẩn
sample_6 = np.random.choice([-1, 2, 3, 4, 5], 30)
print(sample_6)

[ 4  5  3 -1  3  4  2  5  2  4  3  2  3  2  3  3 -1  2  5  5  2  4  3  3
  5  3  2  4  4 -1]


In [ ]:
#SInh ngẫu nhiên chuỗi giá trị sau ['Huế', 'Đà Nẵng', 'Nha Trang', 'Vũng Tàu'] với kích thước 12 theo phân phối chuẩn
sample_7 = np.random.choice(['Huế', 'Đà Nẵng', 'Nha Trang', 'Vũng Tàu'], 12)
print(sample_7)

['Vũng Tàu' 'Đà Nẵng' 'Nha Trang' 'Nha Trang' 'Đà Nẵng' 'Nha Trang'
 'Đà Nẵng' 'Vũng Tàu' 'Đà Nẵng' 'Vũng Tàu' 'Huế' 'Nha Trang']


In [ ]:
#Sinh ngẫu nhiên chuỗi các thành phố ở trên nhưng không theo phân phối chuẩn mà theo đặc tả xác suất sau [0.2, 0.6, 0.4, 0.2]
#Lưu ý: tổng các xác suất của p bằng 1
sample_8 = np.random.choice(['Huế', 'Đà Nẵng', 'Nha Trang', 'Vũng Tàu'], 5, p = [0.2, 0.3, 0.3, 0.2])
print(sample_8)

['Đà Nẵng' 'Huế' 'Nha Trang' 'Nha Trang' 'Nha Trang']


4. Thư viện scipy.stats

Sinh dữ liệu ngẫu nhiên bằng hàm rvs 

In [ ]:
from scipy import stats

#Sinh ngẫu nhiên mẫu theo phân phối chuẩn với mean = 5.5 std = 2.3 và size = 100
sample_9 = stats.norm.rvs(loc = 5.5, scale = 2.3, size = 100)
print(sample_9[:10])

[3.40888625 6.00050963 6.12716657 5.43829398 2.34261796 8.0528202
 4.44416413 4.2515605  7.49963779 5.64517302]


In [ ]:
#Sinh ngẫu nhiên dữ liệu theo phân phối Poisson
sample_10 = stats.poisson.rvs(loc=18,
                              mu=30,
                              size=1000)
print(sample_10[:10])

[36 63 45 53 44 47 52 46 47 44]
